name: CI

on:
  workflow_dispatch:

jobs:
  Build-Demo:
    if: ${{ github.ref == 'refs/heads/demo' }}    
    runs-on: self-hosted
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Get Source
        run: |
          cd /home/ubuntu
          [ -d mobile-web-capture-3 ] && rm -rf mobile-web-capture-3
          git clone --depth 1 -b demo https://github.com/Dynamsoft/mobile-web-capture.git 

      - name: Prepare Files
        run: |
          # Create deploy directory
          mkdir -p /home/ubuntu/mobile-web-capture-3/deploy
          mkdir -p /home/ubuntu/mobile-web-capture-3/deploy/scenarios
          
          # Copy dist folder
          cp -r /home/ubuntu/mobile-web-capture-3/dist /home/ubuntu/mobile-web-capture-3/deploy/
          
          # Copy index.html and assets from demo
          cp /home/ubuntu/mobile-web-capture-3/samples/demo/index.html /home/ubuntu/mobile-web-capture-3/deploy/
          cp -r /home/ubuntu/mobile-web-capture-3/samples/demo/assets /home/ubuntu/mobile-web-capture-3/deploy/
          
          # Copy scenario files
          cp /home/ubuntu/mobile-web-capture-3/samples/scenarios/customized-empty-container.html /home/ubuntu/mobile-web-capture-3/deploy/scenarios/
          cp /home/ubuntu/mobile-web-capture-3/samples/scenarios/use-file-input.html /home/ubuntu/mobile-web-capture-3/deploy/scenarios/
          
          # Copy hello-world.html
          cp /home/ubuntu/mobile-web-capture-3/samples/hello-world.html /home/ubuntu/mobile-web-capture-3/deploy/

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DEMO_SERVER }}
          username: ${{ secrets.FTP_DEMO_USERNAME }}
          password: ${{ secrets.FTP_DEMO_PASSWORD }}
          port: 21 
          local-dir: /home/ubuntu/mobile-web-capture-3/deploy/
          server-dir: /Demo.dynamsoft.com/mobile-web-capture/
